"""Cookie conversion utilities for ytmusic-cli.

This module handles conversion of raw HTTP cookies from headersauth.json
to Netscape cookie format for yt-dlp/MPV integration.
"""

import json
import logging
import time
from pathlib import Path
from typing import Dict, List, Tuple

logger = logging.getLogger(__name__)


def parse_cookie_string(cookie_string: str) -> Dict[str, str]:
    """Parse raw cookie string into name-value pairs.

    Args:
        cookie_string: Raw cookie header string (e.g., "name1=value1; name2=value2")

    Returns:
        Dictionary mapping cookie names to values
    """
    cookies = {}
    if not cookie_string:
        return cookies

    # Split by semicolon and process each cookie
    for cookie_part in cookie_string.split(';'):
        cookie_part = cookie_part.strip()
        if not cookie_part or '=' not in cookie_part:
            continue

        # Split on first '=' only (values might contain '=')
        name, value = cookie_part.split('=', 1)
        cookies[name.strip()] = value.strip()

    return cookies


def get_youtube_domains() -> List[Tuple[str, bool, str, bool]]:
    """Get YouTube domains for cookie placement.

    Returns:
        List of tuples: (domain, include_subdomains, path, secure_only)
    """
    return [
            ('music.youtube.com', False, '/', False),  # YouTube Music specific
            ('.youtube.com', True, '/', False),        # YouTube-wide (subdomains)
            ('youtube.com', False, '/', False),        # YouTube main domain
            ]


def determine_expires(cookie_name: str) -> int:
    """Determine expiration time for a cookie.

    Args:
        cookie_name: Name of the cookie
        cookie_value: Value of the cookie

    Returns:
        Unix timestamp (0 for session cookies)
    """
    # Common session cookie patterns
    session_patterns = ['session', 'token', 'sid', 'auth']
    cookie_lower = cookie_name.lower()

    if any(pattern in cookie_lower for pattern in session_patterns):
        return 0  # Session cookie

    # For persistent cookies, set expiration to 1 year from now
    # YouTube cookies typically last long periods
    return int(time.time()) + (365 * 24 * 60 * 60)


def determine_secure_flag(cookie_name: str) -> bool:
    """Determine if cookie should be secure (HTTPS only).

    Args:
        cookie_name: Name of the cookie

    Returns:
        True if cookie should be secure only
    """
    # YouTube cookies with __Secure- prefix require HTTPS
    secure_patterns = ['__secure-', 'login', 'session']
    cookie_lower = cookie_name.lower()

    return any(pattern in cookie_lower for pattern in secure_patterns)


def convert_cookies_to_netscape(headers_auth_path: str, cookies_output_path: str) -> bool:
    """Convert cookies from headersauth.json to Netscape format.

    Args:
        headers_auth_path: Path to headersauth.json file
        cookies_output_path: Path where cookies.txt should be saved

    Returns:
        True if conversion successful, False otherwise
    """
    try:
        # Read headersauth.json
        headers_path = Path(headers_auth_path)
        if not headers_path.exists():
            logger.error(f"Headers auth file not found: {headers_auth_path}")
            return False

        with open(headers_path, 'r', encoding='utf-8') as f:
            headers_data = json.load(f)

        # Extract Cookie header (try both 'Cookie' and 'cookie' for case-insensitive matching)
        cookie_string = headers_data.get('Cookie') or headers_data.get('cookie', '')
        if not cookie_string:
            logger.warning("No Cookie header found in headersauth.json")
            # Create empty cookies.txt file
            return create_empty_cookies_file(cookies_output_path)

        # Parse cookies
        cookies = parse_cookie_string(cookie_string)
        if not cookies:
            logger.warning("No valid cookies found in Cookie header")
            return create_empty_cookies_file(cookies_output_path)

        # Get YouTube domains
        domains = get_youtube_domains()

        # Create output directory if needed
        output_path = Path(cookies_output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write Netscape cookie file
        with open(output_path, 'w', encoding='utf-8') as f:
            # Write header
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f"# Generated by ytmusic-cli from {headers_auth_path}\n")
            f.write(f"# Generated at: {time.ctime()}\n")
            f.write("# This is an automatically generated file - DO NOT EDIT\n\n")

            # Write cookies for each domain
            for domain, include_subdomains, path, secure_only in domains:
                for cookie_name, cookie_value in cookies.items():
                    expires = determine_expires(cookie_name)
                    cookie_secure = determine_secure_flag(cookie_name) or secure_only

                    # Format: domain\tinclude_subdomains\tpath\tsecure_only\texpires\tname\tvalue
                    line = "\t".join([
                        domain,
                        str(include_subdomains).upper(),
                        path,
                        str(cookie_secure).upper(),
                        str(expires),
                        cookie_name,
                        cookie_value
                        ])
                    f.write(line + "\n")

        logger.info(f"Successfully converted {len(cookies)} cookies to {cookies_output_path}")
        return True

    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in headersauth.json: {e}")
        return False
    except Exception as e:
        logger.error(f"Error converting cookies: {e}")
        return False


def create_empty_cookies_file(cookies_output_path: str) -> bool:
    """Create an empty cookies.txt file.

    Args:
        cookies_output_path: Path where cookies.txt should be saved

    Returns:
        True if successful, False otherwise
    """
    try:
        output_path = Path(cookies_output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by ytmusic-cli - No cookies found\n")
            f.write(f"# Generated at: {time.ctime()}\n")
            f.write("# This is an automatically generated file - DO NOT EDIT\n\n")

        logger.info(f"Created empty cookies file: {cookies_output_path}")
        return True

    except Exception as e:
        logger.error(f"Error creating empty cookies file: {e}")
        return False


def should_convert_cookies(headers_auth_path: str, cookies_output_path: str) -> bool:
    """Check if cookies should be converted based on file timestamps.

    Args:
        headers_auth_path: Path to headersauth.json file
        cookies_output_path: Path to cookies.txt file

    Returns:
        True if conversion should happen, False otherwise
    """
    headers_path = Path(headers_auth_path)
    cookies_path = Path(cookies_output_path)

    # If headers file doesn't exist, no conversion needed
    if not headers_path.exists():
        return False

    # If cookies file doesn't exist, conversion needed
    if not cookies_path.exists():
        return True

    # If headers file is newer than cookies file, conversion needed
    headers_mtime = headers_path.stat().st_mtime
    cookies_mtime = cookies_path.stat().st_mtime

    return headers_mtime > cookies_mtime


def ensure_cookies_file(headers_auth_path: str, cookies_output_path: str) -> bool:
    """Ensure cookies.txt exists and is up-to-date.

    Args:
        headers_auth_path: Path to headersauth.json file
        cookies_output_path: Path to cookies.txt file

    Returns:
        True if cookies file is ready, False otherwise
    """
    if should_convert_cookies(headers_auth_path, cookies_output_path):
        logger.info("Converting cookies to Netscape format...")
        return convert_cookies_to_netscape(headers_auth_path, cookies_output_path)

    # Cookies file exists and is up-to-date
    return True
